### ISSUE TITLE
Using X on the map screen leaves a permanent change

### ISSUE THREAD

**Issue by SenseiLeRoof** [JarnoWesthof/TsRandomizer#10]
v0.9.12, seed independent

If you press X on the (Select) map screen, rooms with items will never lose their orangeness, even after you obtain the items. Orange squares show up on the in-game minimap too.

**Comment by JarnoWesthof** [comment]
Yes thanks for letting me know, i should have a fix for that in a few hours

**Comment by JarnoWesthof** [comment]
It has been resolved in the new version https://github.com/JarnoWesthof/TsRandomizer/releases/tag/v0.9.13
