### ISSUE TITLE
Getting quite a few unbeatable seeds?

### ISSUE THREAD

**Issue by SenseiLeRoof** [JarnoWesthof/TsRandomizer#11]
I can't recall specific examples since I tend to delete them quickly, but there's only been one out of the last eight that I could even get out of Lake Desolation.

**Comment by JarnoWesthof** [comment]
i doubt that,
to get out of lake desolation you eiter use:
time stop, sucabus hairpin, light wall, celestial sash, telaria attachment, pyramid keys

**Comment by SenseiLeRoof** [comment]
None of which are guaranteed to show up in the handful of reachable "treasure spots" in LD, or (in Lightwall's case) to be given in the intro. Six out of all the orbs + all the spells + all the rings + all the equipment + stat-ups + whatever else is not good odds.
