### ISSUE TITLE
Seed 0A390F030000: Softlock in Caves of Banishment

### ISSUE THREAD

**Issue by shaneriley** [JarnoWesthof/TsRandomizer#13]
In the vertical passage on the map indicated below, to continue to the next spot indicated or to backtrack both require double jump, which I do not have by this point.

![Screen Shot 2021-06-14 at 4 57 00 AM](https://user-images.githubusercontent.com/39553/121866864-574da380-cccd-11eb-9217-76935813d0ff.png)

**Comment by JarnoWesthof** [comment]
you indeed need either double jump or lightwall or celestial sash or pyramid kids to get out of there. so i am kinda curius how you got in there and what items you have

but yes sorry this reply is late i hardly ever check the issues tab on github
