### ISSUE TITLE
Empire orb not appearing in inventory

### ISSUE THREAD

**Issue by shaneriley** [JarnoWesthof/TsRandomizer#16]
In seed 0A390F030000, the empire orb doesn't appear in inventory after obtaining it.

![no_empire_orb](https://user-images.githubusercontent.com/39553/122559666-a23d2300-d00d-11eb-940a-d09cc89e9f8e.gif)

**Comment by wafflesoup** [comment]
Yeah that particular spot was causing a couple issues including a crash so it was changed to not be randomized and not actually give an item. The Empire Orb is still located somewhere else in the seed though.

**Comment by shaneriley** [comment]
Yeah, generating the spoiler log revealed it was elsewhere in the map. I'll know to ignore in the future. Thanks.

The randomizer is a wonderful app, by the way. I believe I've played around 15 hours of randomized games already, and the original game only has 10 hours logged in Steam.
