### ISSUE TITLE
Colorblind issue with map colors

### ISSUE THREAD

**Issue by marcmagus** [JarnoWesthof/TsRandomizer#18]
Orange (available check) and Red (save point) are difficult to distinguish for colorblind players.
This particularly causes a problem when there is a lone check in an unvisited region of the map (see attached)
![screenshot-2021-08-18T19:07:24](https://user-images.githubusercontent.com/611523/129983579-fafb718b-cb58-42ac-a82e-174c05415234.png)

**Comment by JarnoWesthof** [comment]
Colorblindess comes in many variations, its not just red/orange it varies from person to person so to properly resolve this there would need to be more color options

**Comment by JarnoWesthof** [comment]
It's in progress

**Comment by JarnoWesthof** [comment]
Will be release with next version
