### ISSUE TITLE
Unbeatable seed

### ISSUE THREAD

**Issue by SenseiLeRoof** [JarnoWesthof/TsRandomizer#3]
Seed: 53B4BE932A, randomizer v0.9.11, TS version 1.032

No source of fire, can't stop time to use enemies as stepping stones, no high-jumping relics, and no time gate access. I've tried everything I can think of except farming the Cheveur Tank to see what it drops.

**Comment by JarnoWesthof** [comment]
Intesting let me test,  Cheveur Tank's will not help you here

**Comment by JarnoWesthof** [comment]
hmmz for me it says 53B4BE932A is unbeatable

**Comment by JarnoWesthof** [comment]
Well a lot has changed in the randomization logic to enabled reverted mode, so lets hope this issue wont happen again
