### ISSUE TITLE
Feature Suggestions/Requests: Additional Settings, Flags, and Enhancements

### ISSUE THREAD

**Issue by RokonShimo** [JarnoWesthof/TsRandomizer#64]
- [ ] **Start with Timespinner Wheel:** Self-explanatory. Useful for beginners and those who want a guaranteed path out of Lake Desolation.
- [ ] **Require Spindle for Time Travel:** The Twin Pyramid Keys do not unlock a warp in the Past until Lunais uses the Timespinner in Varndagray Metropolis. In an Inverted seed, simply collecting the Spindle unlocks a warp in the Present.
- [ ] **Selen Cannot Give Lightwall:** Using the default settings, Lightwall on Selen's Heirloom is the logical path out of Lake Desolation more often than not. This may be either a Flag or always on.
- [ ] **Disable Quest Checks:** Alternatively, if they are disabled by default, enable them.
- [ ] **Vanilla Alchemist:** Collecting Orbs unlocks the respective Spell and Ring as in Vanilla. Selen will always give you a matching set of Orb, Necklace and Ring.
- [ ] **Random Alchemist:** As above, but Ring and Necklace checks are random items.
    - [ ] **Options for Alchemist Prices:**
    - **Vanilla:** The Merchant Crow is guaranteed to sell Essence Crystals, Gold Rings, and Gold Necklaces.
    - **Quick:** Each Ring and Necklace check costs 750 Entropy (or a random amount) instead of Jewelery Parts.
    - **Key:** Jewelry Parts are considered Key Items. There is one of each in the game and they are not consumed when spent.
- [ ] **Equipment Balancing:** Attempts to ensure you do not obtain overpowered equipment too early.
- [ ] **Open Timespinner:** The Calibration Gears are not required to use the rebuilt Timespinner and access ???. They are, however, required to enter Sandman's chamber.
    - [ ] **Open Pyramid:** As above, but collecting the Twin Pyramid Keys will open the Great Pyramid instantly.
    - [ ] **Open Sandman:** As above, but the Calibration Gears are not required to beat the game.
- [ ] **Patricide:** Defeating Emperor Vilete in the present opens the checks for both the Empire Orb and Eternal Brooch, and does not trigger an ending.
- [ ] **Meyef Counts As A Fire Source:** Require players to take control of Meyef to burn vines.
- [ ] **Randomise Starting Partner:** Alternative to "Start With Meyef".

Feel free to flag or reject each of these individually.

**Comment by JarnoWesthof** [comment]
if you use Archipelago for your game, you can already choose your starting item such as Timespinner Wheel, by adding it as your starting inventory

**Comment by JarnoWesthof** [comment]
Closing this as its yo much at the same time, it scares me

**Comment by JarnoWesthof** [comment]
5/
