### ISSUE TITLE
Tried NG+ and crashed on equipping orb

### ISSUE THREAD

**Issue by DracoDynasty** [JarnoWesthof/TsRandomizer#8]
This is possibly normal, since NG+ with randomizer is probably not intended to function properly.

Basically I finished a seed and wanted to see what would happen on NG+.
I don't have the text seed but I can see the representation on my savefile: ![FirstSeed](https://user-images.githubusercontent.com/7428553/111877047-bab38800-89a1-11eb-8f16-fb17c40dfcd5.png)

I noticed that the game let me keep the jewel box and the orbs equipped at the time.
I still had orbs equipped but saw that my orb list was empty.
I dediced to unequip everything from the jewelbox, and equip only the orbs that would be given to me.
When I did, the game crashed.

This is the log: [TsRandomizer 2021-03-20 15.21.txt](https://github.com/JarnoWesthof/TsRandomizer/files/6175880/TsRandomizer.2021-03-20.15.21.txt)

I tried with another seed and the game crashes again as soon as you equip the first orb you get.

I also saw that I still had necklaces and rings in my inventory.
I still had Talaria in my relics, and my pet list was empty but the game still had one equipped.

I just wanted to see if it was possible to NG+ through seeds and keep the character/orb levels through them.

I also understand that NG+ is most likely not intended to work with the randomizer, so it's OK if you don't intend to fix this.

**Comment by JarnoWesthof** [comment]
Intesting, i never tried NG+ myzelf because it indeed makes little sense is a randomizer, the crash does slightly concern me, as i am not sure if its limited to NG+. ill look into it

**Comment by JarnoWesthof** [comment]
NG+ will not be supported at this point (i wont put effort into disabling either)
